### ISSUE TITLE
LG Device Problem: App Crashes on Anonymous Login

### ISSUE THREAD

**Issue by pedroliman** [avaliabrasil/avalia-brasil#16]
The app is crashing after I click on "Anonymous Login". This started to happen in version 1.05 and is still happening on version 1.06. This is happening on my LG Volt LGH422 device.

I'm currently unable to test the app, since I have the "No internet connection" on my virtual device, and I cannot open de app on the real device.

**Comment by pedroliman** [comment]
Android Debug Code:

I/Google Maps Android API: Google Play services client version: 8487000
I/Google Maps Android API: Google Play services package version: 9683236
W/art: Suspending all threads took: 42.206ms
D/FLASH: Couldn't find file:  /data/data/org.avaliabrasil.avaliabrasil2/files/DATA_ServerControlledParametersManager.data.org.avaliabrasil.avaliabrasil2: open failed: ENOENT (No such file or directory)
I/art: Background partial concurrent mark sweep GC freed 3691(233KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 18MB/30MB, paused 1.841ms total 175.301ms
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.avaliabrasil.avaliabrasil2, PID: 20099
                  java.lang.NullPointerException: Attempt to get length of null array
                      at maps.G.a.a(Unknown Source)
                      at maps.V.N.a(Unknown Source)
                      at maps.D.e.a(Unknown Source)
                      at maps.D.p.a(Unknown Source)
                      at maps.ad.ae.a(Unknown Source)
                      at maps.ad.t.a(Unknown Source)
                      at maps.ad.R.a(Unknown Source)
                      at uo.onTransact(:com.google.android.gms.DynamiteModulesB:66)
                      at android.os.Binder.transact(Binder.java:380)
                      at com.google.android.gms.maps.internal.IMapViewDelegate$zza$zza.onCreate(Unknown Source)
                      at com.google.android.gms.maps.MapView$zza.onCreate(Unknown Source)
                      at com.google.android.gms.dynamic.zza$3.zzb(Unknown Source)
                      at com.google.android.gms.dynamic.zza$1.zza(Unknown Source)
                      at com.google.android.gms.maps.MapView$zzb.zzzW(Unknown Source)
                      at com.google.android.gms.maps.MapView$zzb.zza(Unknown Source)
                      at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                      at com.google.android.gms.dynamic.zza.onCreate(Unknown Source)
                      at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
                      at org.avaliabrasil.avaliabrasil2.avb.fragments.main.PlacesMapFragment.onCreateView(PlacesMapFragment.java:67)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                      at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                      at android.view.View.measure(View.java:17496)
                      at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                      at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                      at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                      at android.view.View.measure(View.java:17496)
                      at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                      at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1438)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:724)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:615)
                      at android.view.View.measure(View.java:17496)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5464)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
                    at android.view.View.measure(View.java:1

**Comment by pedroliman** [comment]
Tested recent version on a real device, looks like it's working.
