### ISSUE TITLE
New crash - onItemSelected(RankingActivity.java:280)

### ISSUE THREAD

**Issue by pedroliman** [avaliabrasil/avalia-brasil#56]
Stack trace:

```
10-27 22:23:56.204 21430-21430/org.avaliabrasil.avaliabrasil2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                java.lang.NullPointerException
                                                                                    at org.avaliabrasil.avaliabrasil2.avb.activity.RankingActivity$2.onItemSelected(RankingActivity.java:280)
                                                                                    at android.widget.AdapterView.fireOnSelected(AdapterView.java:899)
                                                                                    at android.widget.AdapterView.selectionChanged(AdapterView.java:882)
                                                                                    at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1050)
                                                                                    at android.widget.AdapterView.handleDataChanged(AdapterView.java:1029)
                                                                                    at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:180)
                                                                                    at android.widget.Spinner.onMeasure(Spinner.java:445)
                                                                                    at android.support.v7.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:407)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1415)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:480)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
                                                                                    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:477)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                                                    at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1075)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1410)
                                                                                    at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                    at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5245)
                                                                                    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2586)
                                                                                    at android.view.View.measure(View.java:16831)
                                                                                    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2189)
                                                                                    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1352)
                                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1535)
                                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
                                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6364)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                                    at android.view.Cho
```

**Comment by pedroliman** [comment]
More log info:
[stack_completo.txt](https://github.com/avaliabrasil/avalia-brasil/files/557339/stack_completo.txt)

**Comment by pedroliman** [comment]
Tested, passing.
